kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-vol
  labels:
    type: local
spec:
  capacity:
    storage: 150M
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/davi_heppi/exercicio/html
    server: 10.142.0.2
    readOnly: false
