apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-02-25T22:18:56Z
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "155769"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: ded10f53-1a79-11e8-b960-42010a8e0002
spec:
  clusterIP: 10.109.215.82
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31212
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
